name: Devbox Update

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    uses: truvity/ci-workflows/.github/workflows/devbox-update.yaml@b14a5741359aebd7ba377d1822651b2d188832e8 # v2.22.1
    secrets: inherit
