name: Devbox Update

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    uses: truvity/ci-workflows/.github/workflows/devbox-update.yaml@6891bcb9c3e9e57dc33dc8dcca0462c32ee4afb6 # v2.22.0
    secrets: inherit
