name: Renovate

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    uses: truvity/ci-workflows/.github/workflows/renovate.yaml@eb317bdb3240d43404665cc943d1c00e8946f733 # v2.18.0
    secrets: inherit
