name: Renovate

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    uses: truvity/ci-workflows/.github/workflows/renovate.yaml@b19968438f6f19b681517c4e2cfcb87fe7887673 # v2.16.3
    secrets: inherit
